// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGx3QZarYZlYKFlCcsFgG3pskmIjw0dUs',
    appId: '1:574784405090:web:995c1c3c64844ba2731b3b',
    messagingSenderId: '574784405090',
    projectId: 'la-butaca-4f97e',
    authDomain: 'la-butaca-4f97e.firebaseapp.com',
    databaseURL: 'https://la-butaca-4f97e-default-rtdb.firebaseio.com',
    storageBucket: 'la-butaca-4f97e.firebasestorage.app',
    measurementId: 'G-XCD60KP61J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzMaBg1Z4in73qYFpPT-GcuBIynK7SpU',
    appId: '1:574784405090:android:0c2c16f374810c2b731b3b',
    messagingSenderId: '574784405090',
    projectId: 'la-butaca-4f97e',
    databaseURL: 'https://la-butaca-4f97e-default-rtdb.firebaseio.com',
    storageBucket: 'la-butaca-4f97e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACxz4mZltBP9_hbG-7wClukqictjjbQXM',
    appId: '1:574784405090:ios:d98dd4d6146304ee731b3b',
    messagingSenderId: '574784405090',
    projectId: 'la-butaca-4f97e',
    databaseURL: 'https://la-butaca-4f97e-default-rtdb.firebaseio.com',
    storageBucket: 'la-butaca-4f97e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxz4mZltBP9_hbG-7wClukqictjjbQXM',
    appId: '1:574784405090:ios:d98dd4d6146304ee731b3b',
    messagingSenderId: '574784405090',
    projectId: 'la-butaca-4f97e',
    databaseURL: 'https://la-butaca-4f97e-default-rtdb.firebaseio.com',
    storageBucket: 'la-butaca-4f97e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGx3QZarYZlYKFlCcsFgG3pskmIjw0dUs',
    appId: '1:574784405090:web:0d9e6040b8f48e92731b3b',
    messagingSenderId: '574784405090',
    projectId: 'la-butaca-4f97e',
    authDomain: 'la-butaca-4f97e.firebaseapp.com',
    databaseURL: 'https://la-butaca-4f97e-default-rtdb.firebaseio.com',
    storageBucket: 'la-butaca-4f97e.firebasestorage.app',
    measurementId: 'G-96Y9YRSH3H',
  );

}